__init__ 
go_home --en cours
get_state
get_current_joints
move_joints

activate_safe_mode
deactivate_safe_mode
start
load_program
power_on
brake_release
get_robot_mode
play_program
stop_program
check_program_running
get_tcp_state
parse_tcp_state_data
parse_joint_data
parse_cartesian_data
parse_tool_data
parse_masterboard_data
bitfield
parse_digital_inputs
parse_digital_outputs
parse_force_data
send_tcp_command
set_digital_out_signal
get_cartesian_pose
move_to_pose
get_tool_data
move_wrt_tool
orientate_wrt_tool
get_digital_inputs
move_with_forces
